# Generated by Django 3.1.5 on 2021-02-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210204_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category_menu',
            field=models.CharField(default='null', max_length=20, verbose_name='Categoría a la que pertenece'),
        ),
    ]
