# Generated by Django 3.1.5 on 2021-02-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210205_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default='texto de prueba', max_length=250, verbose_name='Subtitulo'),
        ),
    ]
