# Generated by Django 3.1.5 on 2021-02-09 19:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=ckeditor.fields.RichTextField(default='texto de prueba', max_length=250, verbose_name='Subtitulo'),
        ),
    ]
