# Generated by Django 3.1.5 on 2021-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210209_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Aparezca en menú principal'),
        ),
    ]
