# Generated by Django 3.1.5 on 2021-02-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
