# Generated by Django 3.1.5 on 2021-02-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
    ]
